### PR TITLE
SC Help Request Controller & Tests for Get & Post

### PR DESCRIPTION
**Pull request by sergioacolis**

### CODE REVIEW

**Comment by jsc103** [comment]
Deployed Branch on Heroku and worked perfect, if all other pitests/jacoco reports are passed LGTM!

**Comment by heyyysus** [comment]
I am not sure if this is a big issue but a small modification in /frontend/package-lock.json is a part of the commit.

**Comment by sergioacolis** [comment]
> I am not sure if this is a big issue but a small modification in /frontend/package-lock.json is a part of the commit.

i checked it out and it's just a curly bracket was moved down by 1 space, non issue
also passes pitests/jacoco reports locally, so i think its ready to merge

**Comment by jcucsb** [comment]
Deploys with no issues on Heroku, passes CI/CD tests, LGTM!

**Pull request merged**
