### PR TITLE
Taeho articles controller

### PR DESCRIPTION
**Pull request by taeho1031**
Finished controller and test for article

### CODE REVIEW

**Comment by YYA0** [comment]
Passed mvn test on local machine. When deployed on Heroku, I failed to post a new article and keep getting <400> error. I checked controller test and it seems to be good. I'm not sure what the problem is.

**Comment by taeho1031** [comment]
> Passed mvn test on local machine. When deployed on Heroku, I failed to post a new article and keep getting <400> error. I checked controller test and it seems to be good. I'm not sure what the problem is.

I'll try to debug what's wrong. Thanks for checking!

**Comment by jcucsb** [comment]
LGTM!

**Review by sergioacolis — APPROVED** [review]
LGTM

**Pull request merged**
